// noinspection BadExpressionStatementJS,JSUnresolvedReference,JSStringConcatenationToES6Template

{
        ab:'Abkhaz Аԥсуа',
        af:'Afrikaans',
        ar:'Arabic العربية',
        as:'Assamese অসমীয়া',
        be:'Belarusian Беларуская',
        bg:'Bulgarian Български',
        bn:'Bengali বাংলা',
        ca:'Catalan Català',
        chr:'Cherokee ᏣᎳᎩ',
        cs:'Czech Český',
        cy:'Welsh Cymraeg',
        da:'Danish Dansk',
        de:'Deutsch German',
        el:'Greek Ελληνικά',
        en:'English',
        enm:'English',
        eo:'Esperanto',
        es:'Spanish Español',
        et:'Estonian Eesti',
        eu:'Basque Euskara',
        fa:'Persian Farsi فارسی',
        fi:'Finnish Suomi',
        fil:'Filipino Tagalog',
        fo:'Faroese Føroyskt',
        fr:'French Français',
        ga:'Irish Gaeilge',
        gl:'Galician Galego',
        gsw:'Swiss German Schweizerdeutsch',
        he:'Hebrew עברית',
        hi:'Hindi हिन्दी',
        hr:'Croatian Hrvatski',
        ht:'Haitian Creole Kreyòl',
        hu:'Hungarian Magyar',
        hy:'Armenian Հայերեն',
        id:'Indonesian Bahasa',
        is:'Icelandic Íslenska',
        it:'Italian Italiano',
        ja:'Japanese 日本語',
        jbo:'Lojban',
        ka:'Georgian ქართული',
        kab:'Kabyle Taqbaylit',
        kk:'Kazakh Қазақша',
        km:'Khmer ភាសាខ្មែរ',
        kn:'Kannada ಕನ್ನಡ',
        ko:'Korean 한국어',
        kw:'Cornish Kernewek',
        ky:'Kyrgyz Кыргызча',
        lb:'Luxembourgish Lëtzebuergesch',
        lt:'Lithuanian Lietuvių',
        lv:'Latvian Latviešu',
        lzh:'Chinese 中文',
        mi:'Maori Māori',
        mk:'Macedonian Македонски',
        ml:'Malayalam മലയാളം',
        mn:'Mongolian Монгол',
        mr:'Marathi मराठी',
        ms:'Malay Melayu',
        mt:'Maltese Malti',
        my:'Burmese Myanmar မြန်မာ',
        nb:'Norwegian Norsk',
        ne:'Nepali नेपाली',
        nl:'Dutch Nederlands',
        nn:'Norwegian Norsk',
        oc:'Occitan',
        or:'Odia ଓଡ଼ିଆ',
        pa:'Punjabi ਪੰਜਾਬੀ',
        pl:'Polish Polski',
        pr:'English',
        pt:'Portuguese Português',
        ro:'Romanian Română',
        ru:'Russian Русский',
        si:'Sinhala සිංහල',
        sk:'Slovak Slovenský',
        sl:'Slovenian Slovenščina',
        sn:'Shona',
        sq:'Albanian Shqip',
        sr:'Serbian Српски',
        sv:'Swedish Svenska',
        sw:'Swahili Kiswahili',
        ta:'Tamil தமிழ்',
        te:'Telugu తెలుగు',
        th:'Thai ไทย',
        tr:'Turkish Türkçe',
        ug:'Uyghur ئۇيغۇرچە',
        uk:'Ukrainian Українська',
        ur:'Urdu اردو',
        uz:'Uzbek Oʻzbekcha',
        vi:'Vietnamese Tiếng Việt',
        zh:'Chinese 中文',
        zu:'Zulu isiZulu'
    };