# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Test Workflow

on:
  repository_dispatch:
    types: [run_test_workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
      - name: Run a one-line script
        run: echo ${{ github.event.client_payload.release_label }}
        
      - name: Get Latest Jellyfin-web
        id: latest-web
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jellyfin
          repo: jellyfin-web
          excludes: prerelease, draft
        
      - name: Get Latest Jellyfin-web PreRelease
        id: latest-web-prereleasee
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jellyfin
          repo: jellyfin-web
          excludes: release, draft
          
      - name: Clone jellyfin-web
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-web'
          platform: 'github'
          path: 'jellyfin-web'
          ref: ${{ steps.latest-web.outputs.release }}
          
      - name: Clone jellyfin-web PreRelease
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-web'
          platform: 'github'
          path: 'jellyfin-web-prerelease'
          ref: ${{ steps.latest-web-prereleasee.outputs.release }}
          
      - run: ls
        
      - name: Set Release Label
        uses: haya14busa/action-cond@v1
        id: label
        with:
          cond: ${{ github.event.client_payload.release_label != 0 }}
          if_true: ${{ github.event.client_payload.release_label }}
          if_false: ${{ steps.date.outputs.date }}
      
      - name: Print Final Label
        run: echo ${{ steps.label.outputs.value }}
        
      - name: Print Release Info
        run: |
          echo ${{ github.event.client_payload.data.webRelease.name }}
          echo ${{ github.event.client_payload.data.webPreRelease.name }}
